---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
  name: terraforms.alustan.io
spec:
  group: alustan.io
  names:
    kind: Terraform
    listKind: TerraformList
    plural: terraforms
    singular: terraform
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Terraform is the Schema for the terraforms API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: TerraformSpec defines the desired state of Terraform
            properties:
              containerRegistry:
                description: ContainerRegistry defines the container registry settings
                properties:
                  imageName:
                    type: string
                  provider:
                    type: string
                  semanticVersion:
                    type: string
                required:
                - imageName
                - provider
                - semanticVersion
                type: object
              postDeploy:
                description: PostDeploy defines the post-deployment actions
                properties:
                  args:
                    additionalProperties:
                      type: string
                    type: object
                  script:
                    type: string
                required:
                - args
                - script
                type: object
              scripts:
                description: Scripts defines the deployment and destruction scripts
                properties:
                  deploy:
                    type: string
                  destroy:
                    type: string
                required:
                - deploy
                - destroy
                type: object
              variables:
                additionalProperties:
                  type: string
                type: object
            required:
            - containerRegistry
            - postDeploy
            - scripts
            - variables
            type: object
          status:
            description: TerraformStatus defines the observed state of Terraform
            properties:
             
              message:
                type: string
              observedGeneration:
                type: integer
              
              postDeployOutput:
                additionalProperties:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                type: object
              state:
                type: string
            required:
            - message
            - state
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
