apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terraform-manager-binding
subjects:
- kind: ServiceAccount
  name: {{  .Values.serviceAccount.name }}
  namespace: alustan
roleRef:
  kind: ClusterRole
  name: terraform-manager
  apiGroup: rbac.authorization.k8s.io

