apiVersion: v1
kind: Service
metadata:
  name: terraform-controller-helm
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "terraform-controller-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.infra.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "terraform-controller-helm.selectorLabels" . | nindent 4 }}
